"""Stage parsed source material for the agent when a card exceeds the
prompt-loaded budget.

When ``import.py`` encounters a card whose rendered SOUL.md or
HERMES.md would exceed the 15k threshold, the script does **not** shell
out to any LLM. Instead it:

1. Parses, sanitizes, and (when relevant) sub-header-splits the source
   card's text fields.
2. Writes the result to ``cards/<stem>/source.md`` — a self-describing
   markdown view the agent can read with its own file tool.
3. Raises :class:`NeedsAgentCategorizationError`, which the script
   converts to exit code 2 plus a message pointing at the SKILL.md
   procedure.

The agent then performs the V2-aligned categorization in its own LLM
context (using whatever tools it has), writes one
``extended/<category>.md`` per category, and runs ``finalize.py`` to
assemble the curated SOUL.md / indexed HERMES.md from those files.

This module is the dividing line between deterministic script work
(parse / sanitize / scan / write source.md) and agent-driven LLM work.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from .classify import _detect_subheaders
from .extended import write_lorebook_payloads
from .sanitize import sanitize
from .substitute import substitute


class NeedsAgentCategorizationError(Exception):
    """Raised when a card is too large to ship as-is and the CLI has
    written ``source.md`` for the agent to redistribute.

    Carries the data the CLI needs to format a helpful error message
    for the user / agent: where the source material is, the character
    name, and how big the rendered output would have been.
    """

    def __init__(
        self,
        *,
        char_name: str,
        source_md_path: Path,
        rendered_size: int,
        threshold: int,
    ) -> None:
        super().__init__(
            f"{char_name}: rendered output is {rendered_size} chars "
            f"(over {threshold}); agent categorization required"
        )
        self.char_name = char_name
        self.source_md_path = source_md_path
        self.rendered_size = rendered_size
        self.threshold = threshold


def _format_field_block(
    field: str,
    value: str,
    *,
    char_name: str,
    user_noun: str,
) -> str | None:
    """Format one V2 field as a section in source.md.

    For ``description`` specifically, sub-header detection runs first;
    when sub-headers are present (e.g. Veranna's ``Full Name: ...``,
    ``Appearance: ...``, ``Personality: ...``), they're preserved as
    ``### Header`` blocks so the agent gets a structurally-flagged input
    instead of one undifferentiated wall.
    """
    if not isinstance(value, str) or not value.strip():
        return None

    cleaned = sanitize(substitute(value, char_name, user_noun))

    if field == "description":
        subheaders = _detect_subheaders(cleaned)
        if subheaders:
            parts = ["## description (already structured by subheaders)\n"]
            for header, body in subheaders:
                parts.append(f"### {header}\n\n{body}\n")
            return "\n".join(parts)

    return f"## {field}\n\n{cleaned}\n"


def format_source_for_agent(
    data: dict[str, Any],
    *,
    char_name: str,
    user_noun: str,
) -> str:
    """Render the parsed card as a self-describing markdown document the
    agent reads to perform V2 categorization."""
    parts: list[str] = []
    parts.append(f"# {char_name} — source material\n")
    parts.append(
        "> Auto-generated by `import.py` when the rendered "
        "output exceeded the 15k threshold. See **\"Oversized card "
        "procedure\"** in `soultavern/SKILL.md` for what to do with "
        "this material — short version: redistribute into V2 categories "
        "under `extended/<category>.md` (faithful to source wording), "
        "then run `finalize.py`.\n"
    )

    for field in (
        "description",
        "personality",
        "scenario",
        "first_mes",
        "mes_example",
        "system_prompt",
        "post_history_instructions",
    ):
        block = _format_field_block(
            field, data.get(field, ""),
            char_name=char_name, user_noun=user_noun,
        )
        if block:
            parts.append(block)

    greetings = data.get("alternate_greetings") or []
    if isinstance(greetings, list):
        for i, greeting in enumerate(greetings, start=1):
            if not isinstance(greeting, str) or not greeting.strip():
                continue
            cleaned = sanitize(substitute(greeting, char_name, user_noun))
            parts.append(f"## alternate_greeting #{i}\n\n{cleaned}\n")

    book = data.get("character_book")
    if isinstance(book, dict):
        entries = book.get("entries") or []
        if entries:
            parts.append("## character_book\n")
            for i, entry in enumerate(entries, start=1):
                if not isinstance(entry, dict):
                    continue
                content = entry.get("content")
                if not isinstance(content, str) or not content.strip():
                    continue
                comment = entry.get("comment") or ""
                keys = entry.get("keys") or []
                label = comment or (keys[0] if keys else f"entry {i}")
                cleaned = sanitize(substitute(content, char_name, user_noun))
                keys_line = ", ".join(keys) if keys else ""
                parts.append(f"### {label}\n")
                if keys_line:
                    parts.append(f"<!-- keys: {keys_line} -->\n")
                parts.append(f"{cleaned}\n")

    return "\n".join(parts).rstrip() + "\n"


def write_source_md(
    extended_dir: Path,
    data: dict[str, Any],
    *,
    char_name: str,
    user_noun: str,
) -> Path:
    """Write ``source.md`` for the agent **and** the deterministic
    per-entry payloads (``alternate_greetings/``, ``lore/``) into
    ``extended_dir``. Returns the path to ``source.md``.

    The per-entry payloads are written here — not deferred to
    ``finalize`` — because they're already structured per-entry in the
    source card and don't need any LLM judgement. Writing them up-front
    narrows the agent's job to V2 categorization of the unstructured
    prose fields (``description`` / ``personality`` / ``scenario`` /
    ``first_mes`` / ``mes_example`` / ``system_prompt`` /
    ``post_history_instructions``).
    """
    extended_dir.mkdir(parents=True, exist_ok=True)
    # source.md lives in the per-card directory (parent of extended/),
    # so the agent finds it and the future extended/ files side-by-side.
    target = extended_dir.parent / "source.md"
    body = format_source_for_agent(data, char_name=char_name, user_noun=user_noun)
    target.write_text(body, "utf-8")
    write_lorebook_payloads(extended_dir, data, user_noun=user_noun)
    return target
